name: moodle
type: php:7.0
disk: 2048
build:
  flavor: composer
runtime:
  extensions:
    - xmlrpc 
mounts:
  'moodledata': 'shared:files/moodledata'
relationships:
  database: mysqldb:mysql
web:
  locations:
    '/':
      root: 'public'
      passthru: /index.php
      allow: true
    '/uploads':
      root: 'public'
      allow: false
crons:
  default:
    spec: '* * * * *'
    cmd: 'php ./public/admin/cli/cron.php >/dev/null'