name: moodle
type: php:7.0
disk: 2048
mounts:
  'uploads': 'shared:files/uploads'
relationships:
  database: mysqldb:mysql
web:
  locations:
    '/':
      root: ''
      passthru: /index.php
      allow: true
    '/uploads':
      root: ''
      allow: false
crons:
  default:
    spec: '* * * * *'
    cmd: 'php ./admin/cli/cron.php >/dev/null'